### ISSUE TITLE
java.lang.AssertionError after switching to RFG

### ISSUE THREAD

**Issue by ah-OOG-ah** [GTNewHorizons/RetroFuturaGradle#1]
Mod in question is https://github.com/ah-OOG-ah/GregtorioOverlays.

Steps to replicate:
 - Pull latest from GregtorioOverlays/master and ExampleMod/wip-rfg-tests
 - Run `./update ../GregtorioOverlays/` in cloned ExampleMod repo (assuming you keep all your repos in one directory)
 - Import project into IntelliJ and execute `runClient` with IntelliJ
 
 Log file is here: https://pastebin.com/H9JUbdw0

**Comment by eigenraven** [comment]
Should be fixed in the rfg update I just published, now assertions are only enabled in the current mod and not all loaded java packages.
