### ISSUE TITLE
Per-run working directory

### ISSUE THREAD

**Issue by slava110** [GTNewHorizons/RetroFuturaGradle#30]
Working directory should be configurable for each run configuration instead of using one for all of them. Also server run directory should be separate by default (named `run-server` for example).
This will not only remove mess in the `run` directory (having both client and server files in the same folder is awful) but it will also fix https://github.com/CleanroomMC/TemplateDevEnv/issues/14

**Comment by slava110** [comment]
Just to be clear: folders for native files should be separate too. Because it was the cause of https://github.com/CleanroomMC/TemplateDevEnv/issues/14. Multiple processes are trying to use same natives basically and they can't :I

**Comment by Glease** [comment]
Stumbed upon this problem too. It turns out you can workaround this by setting tasks.runClient.workingDir or tasks.runServer.workingDir in your build.gradle.

**Comment by eigenraven** [comment]
The natives issue should be fixed by RFG 1.3.20. Run folders can be easily changed by editing the workingDir property of the run tasks, and the default merged folders should no longer crash on windows :crossed_fingers:
