### ISSUE TITLE
Is 1.8.9, 1.9.4, 1.10.2 and 1.11.2 support planned?

### ISSUE THREAD

**Issue by Hummel009** [GTNewHorizons/RetroFuturaGradle#53]
This great plugin currently supports versions 1.7.10 and 1.12.2. All the versions after 1.12.2 are compatible with modern forge gradle plugin, versions before 1.6.4 are supported by voldeloom plugin. But versions between 1.7.10 and 1.12.2 aren't supported by any plugin, they need ultra-old gradle and setupDecompWorkspace command with usage of ide files instead of gradle workspace. Is 1.8.9, 1.9.4, 1.10.2 and 1.11.2 support planned? It would be wonderful if you were able to make support for these versions.

**Comment by tr7zw** [comment]
I just lost it after spending hours setting up 1.12.2, assuming there is 1.8.9 support because there is 1.7.10 support... Guess time to try to hack it in, most places seem to be just switches with 1.7.10/1.12.2 hardcoded values, so adding more *should* be doable.

**Comment by eigenraven** [comment]
Personally I don't have enough time to implement&validate RFG for all these versions, but if someone does the bulk of the porting work PRs would be welcome.
