### ISSUE TITLE
RFG 1.2.6+ not working with CustomNPCs mod in dev env

### ISSUE THREAD

**Issue by drori200** [GTNewHorizons/RetroFuturaGradle#54]
I discussed this topic before on the discord [here](https://discord.com/channels/181078474394566657/603348502637969419/1192786049009725490)
Basically. commit https://github.com/GTNewHorizons/RetroFuturaGradle/commit/3a01c69db57fa41a9a9950bc8132137db6b49a51 broke the custom npcs mod in dev env and causes it to crash with this error:
https://mcpaste.io/1abb14f2b6a86562

The error has never happened before 1.3.26 and upto 1.3.25 (including it) the mod is running fine

**Comment by bombcar** [comment]
https://github.com/KAMKEEL/CustomNPC-Plus is the mod
