### ISSUE TITLE
README is innacurate

### ISSUE THREAD

**Issue by ah-OOG-ah** [GTNewHorizons/RetroFuturaGradle#63]
> For a much more complex buildscript with more features, check out the [GTNH buildscript](https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/master/build.gradle).

look inside GTNH buildscript
```groovy
//version: 1707058017

plugins {
    id 'com.gtnewhorizons.gtnhconvention'
}
```
???

**Comment by Caedis** [comment]
should probably just point to https://github.com/GTNewHorizons/GTNHGradle
