### ISSUE TITLE
Version 1.20 and minor version 1.20.1 and 1.20.2 support please

### ISSUE THREAD

**Issue by john1234brown** [GTNewHorizons/RetroFuturaGradle#67]
Id love to utilize this but i really need for support for version 1.20.1 and 1.20.2

**Comment by eigenraven** [comment]
MCPConfig-based toolchain (and whatever the NeoForge replacement is called now) is not planned, but if someone else is willing to do the research&implementation work needed to support it, I'd be open to a discussion
